services:
  mariadb:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: travelmind
      MARIADB_USER: app
      MARIADB_PASSWORD: apppass
    volumes:
      - dbdata:/var/lib/mysql
    ports: ["3306:3306"]
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -u$$MARIADB_USER -p$$MARIADB_PASSWORD --silent"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  web:
    build:
      context: .                 # <— root
      dockerfile: apps/web/Dockerfile
    env_file: .env
    depends_on:
      - api
    ports: ["3000:3000"]
    expose: ["3001"]

  api:
    build:
      context: .                 # <— root
      dockerfile: apps/api/Dockerfile
    env_file: .env
    depends_on:
      - mariadb
      - redis
    ports: ["3001:3001"]

  nginx:
    image: nginx:alpine
    volumes:
      - ./apps/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - api
    ports: ["80:80"]

  mobile:
    build:
      context: .                      # <-- root of repo (important)
      dockerfile: apps/mobile/Dockerfile
    environment:
      EXPO_PUBLIC_API_URL: ${EXPO_PUBLIC_API_URL:-http://96.30.194.54:3001}
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0     # serve DevTools to host
      CHOKIDAR_USEPOLLING: 1                    # watch files via volume
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    depends_on:
      - api
    stdin_open: true
    tty: true
    volumes:
      - ./apps/mobile:/app/apps/mobile
      - /app/node_modules
    command: >
      sh -lc "npm ci --workspaces --include-workspace-root || true &&
              npx expo start --tunnel"

volumes:
  dbdata:
